const https = require('https');
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf-8').split('\n').forEach(line => {
    const idx = line.indexOf('=');
    if (idx > 0) process.env[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  });
}

const configPath = path.join(__dirname, '..', 'followups.json');
const REPO = 'ckootelescope/telescopeoutreach';
const GH_PAT = process.env.GH_PAT;

function ghApi(method, apiPath, body) {
  return new Promise((resolve, reject) => {
    const opts = {
      hostname: 'api.github.com',
      path: '/repos/' + REPO + apiPath,
      method,
      headers: {
        'Authorization': 'Bearer ' + GH_PAT,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'telescopeoutreach'
      }
    };
    if (body) opts.headers['Content-Type'] = 'application/json';
    const req = https.request(opts, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => {
        if (res.statusCode >= 400) reject(new Error(res.statusCode + ': ' + d));
        else resolve(JSON.parse(d));
      });
    });
    req.on('error', reject);
    if (body) req.write(JSON.stringify(body));
    req.end();
  });
}

const newEntries = [
  // EDWIN - Email 2, 3, 4
  { slug: "edwin", company: "Edwin", founder: "Peter Rogers", email: "peter@edwingov.com", domain: "edwingov.com", threadId: "19e84ecff815ec50", messageId: "19e84ecff815ec50", subject: "Telescope <> Edwin Intro", body: "<div>Hey Peter, circling back on this. I was looking at the benchmarking tool you guys built, where treasurers can compare their portfolio against similar-sized agencies by region. I think that's a really smart wedge into the sale because it gives someone a reason to engage before they've even committed to switching anything. Curious how you're seeing adoption there and whether it's pulling in inbound interest or if it's more of a sales enablement tool once you're already in a conversation.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "edwin", company: "Edwin", founder: "Peter Rogers", email: "peter@edwingov.com", domain: "edwingov.com", threadId: "19e84ecff815ec50", messageId: "19e84ecff815ec50", subject: "Telescope <> Edwin Intro", body: "<div>Hey Peter, was thinking more about Edwin and the go-to-market here. One thing that stands out to me is the neutrality angle, the fact that you integrate across multiple banks and ERPs without favoring any vendor. I think that matters a lot in local government where the procurement process already has enough friction without worrying about lock-in. The part I keep coming back to is the sales cycle though. You're selling to finance directors and treasurers at municipalities, which can be a long process. I'd be curious how you're navigating that and whether you've found certain city sizes or regions where the pain is acute enough that they move faster.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "edwin", company: "Edwin", founder: "Peter Rogers", email: "peter@edwingov.com", domain: "edwingov.com", threadId: "19e84ecff815ec50", messageId: "19e84ecff815ec50", subject: "Telescope <> Edwin Intro", body: "<div>Hey Peter, one more note. I've been spending time in adjacent govtech and vertical fintech areas, and happy to connect you with folks in our network who've navigated the municipal sales cycle if that'd be useful. The setup time you guys advertise (days, not months) feels like it could be a real differentiator in a market where implementation risk is usually the biggest blocker. Would love to swap notes even if timing isn't right for fundraising. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // ALPA - Email 2, 3, 4
  { slug: "alpa", company: "Alpa", founder: "Anton Soulier", email: "anton@alpacap.com", domain: "getalpa.com", threadId: "19e84ed79f6fe45c", messageId: "19e84ed79f6fe45c", subject: "Telescope <> Alpa Intro", body: "<div>Hey Anton, circling back on this. I was looking at how you guys deliver a weekly P&L to operators every Monday morning by pulling from POS, banking, and supplier invoices automatically. I think that's the right approach because most restaurant owners don't need a dashboard, they need someone to just tell them what happened last week. Curious whether you're seeing more traction with single-location operators or multi-site groups at this stage.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "alpa", company: "Alpa", founder: "Anton Soulier", email: "anton@alpacap.com", domain: "getalpa.com", threadId: "19e84ed79f6fe45c", messageId: "19e84ed79f6fe45c", subject: "Telescope <> Alpa Intro", body: "<div>Hey Anton, been thinking more about Alpa and the go-to-market here. The stat you guys reference, that 79% of restaurant operators want real-time data but only 27% can track basic KPIs, really illustrates the gap. What I think is interesting about your approach is that you're not asking operators to change how they work. You plug into their existing POS and bank feeds and just surface the answers. Having Jerome Tafani on the board makes a lot of sense too given his time running Burger King France and the McDonald's Europe finance side. I'd be curious how you're thinking about the US market and whether the POS landscape here (Toast, Square, Clover) changes the product at all versus what you've built for the UK.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "alpa", company: "Alpa", founder: "Anton Soulier", email: "anton@alpacap.com", domain: "getalpa.com", threadId: "19e84ed79f6fe45c", messageId: "19e84ed79f6fe45c", subject: "Telescope <> Alpa Intro", body: "<div>Hey Anton, one more thought. Given your background building Taster, you've already lived through the pain of managing multi-location restaurant economics firsthand, which I think matters a lot in a product like this. We've spent time around vertical fintech plays in other industries and happy to connect you with founders who've tackled similar problems in different verticals if that'd be useful. Would love to chat even if fundraising isn't on the near-term roadmap. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // ALGUNA - Email 2, 3, 4
  { slug: "alguna", company: "Alguna", founder: "Aleks Djekic", email: "aleks@alguna.io", domain: "alguna.com", threadId: "19e84edcefd709dc", messageId: "19e84edcefd709dc", subject: "Alguna + Telescope", body: "<div>Hey Aleks, circling back on this. I was looking at the Haven AI case study where they cut billing prep time by 80% after switching to you guys. I think that speaks to a real pain point, especially for AI companies where usage-based billing adds a ton of complexity that most teams just hack together with scripts and spreadsheets. Curious how much of the initial pull is coming from AI-native companies versus more traditional SaaS at this point.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "alguna", company: "Alguna", founder: "Aleks Djekic", email: "aleks@alguna.io", domain: "alguna.com", threadId: "19e84edcefd709dc", messageId: "19e84edcefd709dc", subject: "Alguna + Telescope", body: "<div>Hey Aleks, been thinking more about Alguna and the positioning here. The quote-to-cash unification angle is interesting because I think most companies in this space pick a lane, either CPQ or billing, and then try to bolt on the other side later. The fact that you and Jamie both came from Primer and saw the payment orchestration side firsthand probably shaped that thinking. One thing I'd love to understand better is how the 30-day implementation works in practice. When a company like ComplyAdvantage launches a PLG engine through you guys without engineering resources, what does that migration actually look like from their existing billing setup? That seems like where most competitors get stuck.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "alguna", company: "Alguna", founder: "Aleks Djekic", email: "aleks@alguna.io", domain: "alguna.com", threadId: "19e84edcefd709dc", messageId: "19e84edcefd709dc", subject: "Alguna + Telescope", body: "<div>Hey Aleks, one more note. We've worked with a few companies navigating the billing and monetization layer at scale, and I think the AI agent pricing question in particular is going to be a big deal over the next couple years as more companies try to figure out how to charge for non-deterministic workloads. Happy to connect you with relevant folks in our network if useful. Would love to find time for a call even if fundraising isn't top of mind right now. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // INTERNET BACKYARD - Email 2, 3, 4
  { slug: "internet_backyard", company: "Internet Backyard", founder: "Mai Trinh", email: "mai@internetbackyard.com", domain: "internetbackyard.com", threadId: "19e84ee5a220529f", messageId: "19e84ee5a220529f", subject: "Telescope <> Internet Backyard Intro", body: "<div>Hey Mai, circling back on this. I was reading your piece on why a token isn't actually a commodity, the argument that identical token counts reflect totally different economics depending on model size, hardware, and infrastructure choices. I think that framing is really clear and gets at why the financial layer needs to sit beneath the token, not on top of it. Curious whether data center operators or the AI companies buying compute are driving more of the initial pull for gnomos.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "internet_backyard", company: "Internet Backyard", founder: "Mai Trinh", email: "mai@internetbackyard.com", domain: "internetbackyard.com", threadId: "19e84ee5a220529f", messageId: "19e84ee5a220529f", subject: "Telescope <> Internet Backyard Intro", body: "<div>Hey Mai, been thinking more about Internet Backyard and the broader market timing here. The comparison to where oil was before NYMEX standardized pricing is interesting because it implies compute needs a similar moment where the industry agrees on a unit of measurement before any real financial market can form around it. The performance-based pricing angle over GPU-specific pricing feels right to me, because at the end of the day customers are buying throughput, not hardware. I'd be curious how you're thinking about the geographic expansion piece. You mentioned Africa and Southeast Asia alongside North America, and I imagine the standardization problem looks pretty different in markets where the infrastructure is still being built versus where it already exists.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "internet_backyard", company: "Internet Backyard", founder: "Mai Trinh", email: "mai@internetbackyard.com", domain: "internetbackyard.com", threadId: "19e84ee5a220529f", messageId: "19e84ee5a220529f", subject: "Telescope <> Internet Backyard Intro", body: "<div>Hey Mai, one more thought. We've spent time around infrastructure and fintech companies and I think the financial translation layer concept you're building is one of those things that feels obvious in hindsight but requires someone to actually go build it. The fact that over $11 billion has already been lent against GPU fleets suggests the capital side is ready but the tooling hasn't caught up. Happy to connect you with relevant folks in our network who are thinking about compute financing from the capital markets side if that'd be useful. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // RAMAIN - Email 2, 3, 4
  { slug: "ramain", company: "RamAIn", founder: "Shourya Vir Jain", email: "shourya@ramain.ai", domain: "ramain.ai", threadId: "19e84eeb8d785bdb", messageId: "19e84eeb8d785bdb", subject: "UI automation for legacy systems | Telescope intro", body: "<div>Hey Shourya, circling back on this. I was looking at how your agents learn UI policies and interface structures rather than deciding action-by-action, which I think is a smart distinction vs. the computer-use agents from OpenAI/Anthropic/Google. Curious how much of the self-healing actually works in practice when a portal completely redesigns its layout vs. just moving a button around.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "ramain", company: "RamAIn", founder: "Shourya Vir Jain", email: "shourya@ramain.ai", domain: "ramain.ai", threadId: "19e84eeb8d785bdb", messageId: "19e84eeb8d785bdb", subject: "UI automation for legacy systems | Telescope intro", body: "<div>Hey Shourya, been thinking more about the insurance and healthcare use cases on your site. Those carrier portals and payer systems are notoriously painful because every single one has a different UI, different login flow, different way of submitting the same form. Feels like the kind of problem where the real moat isn't the AI model itself but the library of portal-specific knowledge you build up over time as you onboard more customers.<br><br>I'd be curious whether you're seeing faster deployment times as you add more clients in the same vertical, or if each portal is still mostly a fresh setup.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "ramain", company: "RamAIn", founder: "Shourya Vir Jain", email: "shourya@ramain.ai", domain: "ramain.ai", threadId: "19e84eeb8d785bdb", messageId: "19e84eeb8d785bdb", subject: "UI automation for legacy systems | Telescope intro", body: "<div>Hey Shourya, one more thought. We've spent time around a few companies in the procurement and supply chain space where teams are still manually entering data across vendor portals, ERPs, and legacy finance systems. Happy to make intros if any of those connections would be useful as you think about go-to-market.<br><br>If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // QUASH - Email 2, 3, 4
  { slug: "quash", company: "Quash", founder: "Yoel Gavlovski", email: "yoel@quash.ai", domain: "quash.ai", threadId: "19e84eee089017d7", messageId: "19e84eee089017d7", subject: "alternative credit scoring | Telescope intro", body: "<div>Hey Yoel, circling back on this. I was looking at the Credy tool and I think the idea of letting loan officers ask questions in plain English instead of needing a data team to run every analysis is really interesting. Curious how much of the adoption is loan officers actually using it day-to-day vs. it being more of a back-office tool right now.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "quash", company: "Quash", founder: "Yoel Gavlovski", email: "yoel@quash.ai", domain: "quash.ai", threadId: "19e84eee089017d7", messageId: "19e84eee089017d7", subject: "alternative credit scoring | Telescope intro", body: "<div>Hey Yoel, been thinking more about the US credit union push. The average credit union member is 51, and these institutions know they need to attract younger borrowers who expect the same experience they get from a Cash App or a SoFi. But most credit unions don't have the data science teams to build their own models, so they're stuck with the same bureau scores that reject the exact people they're trying to reach.<br><br>I think what's interesting about your approach is that you can drop in pre-trained models via API rather than asking a 50-person credit union to build an ML pipeline from scratch. I'd be curious how the sales cycle looks with credit unions vs. the Latin American banks you've been working with, since the decision-making process is so different.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "quash", company: "Quash", founder: "Yoel Gavlovski", email: "yoel@quash.ai", domain: "quash.ai", threadId: "19e84eee089017d7", messageId: "19e84eee089017d7", subject: "alternative credit scoring | Telescope intro", body: "<div>Hey Yoel, last thought from me. We know the fintech lending space pretty well and have a few connections in the credit union world that might be useful as you build out the US side. Happy to make some intros if that would be helpful.<br><br>If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // EKKO - Email 2, 3, 4
  { slug: "ekko", company: "Ekko", founder: "Oli Cook", email: "oli@ekko.earth", domain: "ekko.earth", threadId: "19e84f0e374822bb", messageId: "19e84f0e374822bb", subject: "Telescope <> Ekko Intro", body: "<div>Hey Oli, circling back on this. I saw you guys just set up the Atlanta office for the US push, and the Worldpay partnership is a great distribution channel. Curious whether the US strategy is more about going through payment processors like Worldpay or signing banks directly.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "ekko", company: "Ekko", founder: "Oli Cook", email: "oli@ekko.earth", domain: "ekko.earth", threadId: "19e84f0e374822bb", messageId: "19e84f0e374822bb", subject: "Telescope <> Ekko Intro", body: "<div>Hey Oli, been thinking more about the merchant side of what you guys are doing. The plugin that shows carbon impact at checkout and lets customers add a small donation is interesting because it turns sustainability into a conversion tool for the merchant, not just a feel-good feature. I think the harder question is whether merchants actually see measurable lift in checkout completion or repeat purchases, because that's what gets them to keep it turned on.<br><br>I'd be curious if you're seeing data on that from the Worldpay merchants or the Shopify integration, and whether the value prop to merchants is more about brand differentiation or actual revenue impact.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "ekko", company: "Ekko", founder: "Oli Cook", email: "oli@ekko.earth", domain: "ekko.earth", threadId: "19e84f0e374822bb", messageId: "19e84f0e374822bb", subject: "Telescope <> Ekko Intro", body: "<div>Hey Oli, one more thought. We know a few folks in the US payments and fintech space who might be worth connecting with as you build out the Atlanta operation. Happy to make some intros if that would be useful.<br><br>If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // TRAZA - Email 2, 3, 4
  { slug: "traza", company: "Traza", founder: "Silvestre Jara Montes", email: "silver@traza.ai", domain: "traza.ai", threadId: "19e84f15c326a4b0", messageId: "19e84f15c326a4b0", subject: "procurement automation | Telescope intro", body: "<div>Hey Silvestre, circling back on this. I was looking at how your agents handle supplier substitutions on change orders, specifically the part where they verify certifications and re-run compliance before issuing a new RFQ. That feels like the step where most procurement teams lose days because it's all manual back-and-forth with the supplier. Curious how much of that you can actually automate end-to-end vs. where a human still needs to step in.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "traza", company: "Traza", founder: "Silvestre Jara Montes", email: "silver@traza.ai", domain: "traza.ai", threadId: "19e84f15c326a4b0", messageId: "19e84f15c326a4b0", subject: "procurement automation | Telescope intro", body: "<div>Hey Silvestre, been thinking more about the construction use case. In that world, a spec change on a project can cascade into dozens of supplier swaps, and procurement teams are usually managing that across spreadsheets and email threads while the project timeline keeps moving. The stat in your blog about procurement contracts losing 11% of their value after signing because of operational gaps feels right, especially when you see how much slippage happens between the PO and what actually gets delivered.<br><br>I'd be curious whether construction is becoming a bigger part of the pipeline vs. manufacturing, and whether the deployment process looks different across those two verticals.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "traza", company: "Traza", founder: "Silvestre Jara Montes", email: "silver@traza.ai", domain: "traza.ai", threadId: "19e84f15c326a4b0", messageId: "19e84f15c326a4b0", subject: "procurement automation | Telescope intro", body: "<div>Hey Silvestre, one more thought. I work closely with Chris Gaertner who has spent a lot of time in the supply chain and manufacturing space through companies like Parabola, Paperless Parts, and Project44. Happy to connect you two if it would be helpful to compare notes on selling into procurement teams at large industrials.<br><br>If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // BALANCEDTRUST - Email 2, 3, 4
  { slug: "balancedtrust", company: "BalancedTrust", founder: "Travis Dulaney", email: "tdulaney@balanced-trust.com", domain: "balanced-trust.com", threadId: "19e84f1aa8a3cff4", messageId: "19e84f1aa8a3cff4", subject: "bank-fintech compliance | Telescope intro", body: "<div>Hey Travis, circling back on this. I was looking at the Coinbax partnership and I think the approach of embedding compliance checks directly into the settlement layer is interesting rather than bolting it on after the fact. Curious how banks are reacting to that model vs. the traditional approach of running compliance as a separate workflow.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "balancedtrust", company: "BalancedTrust", founder: "Travis Dulaney", email: "tdulaney@balanced-trust.com", domain: "balanced-trust.com", threadId: "19e84f1aa8a3cff4", messageId: "19e84f1aa8a3cff4", subject: "bank-fintech compliance | Telescope intro", body: "<div>Travis, been thinking more about BalancedTrust since my last note. One thing I find interesting is how you're positioning around the bank-fintech relationship specifically. Most compliance tools I've seen are built for one side or the other, but the messy part is usually the handoff between the two, especially when you get into fourth-party risk and neither side has full visibility. The fact that your team has Kimberly from OCC and David from Fiserv feels like it matters here since you're building for both sides of that equation. I'd be curious whether you're seeing more pull from the bank side or the fintech side, and whether the sales motion is different for each.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "balancedtrust", company: "BalancedTrust", founder: "Travis Dulaney", email: "tdulaney@balanced-trust.com", domain: "balanced-trust.com", threadId: "19e84f1aa8a3cff4", messageId: "19e84f1aa8a3cff4", subject: "bank-fintech compliance | Telescope intro", body: "<div>Travis, wanted to follow up one more time. I work closely with Chris Gaertner who has spent time around insurance compliance (iLife, etc.) and has seen firsthand how the regulatory automation space plays out across different financial verticals. Happy to connect you two if it would be useful to swap notes on GTM or just have another sounding board. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // KOTINI - Email 2, 3, 4
  { slug: "kotini", company: "Kotini", founder: "Kieran Witt", email: "kieran@kotini.co.uk", domain: "kotini.co.uk", threadId: "19e84f1e1cc54b65", messageId: "19e84f1e1cc54b65", subject: "proptech compliance | Telescope intro", body: "<div>Hey Kieran, circling back on this. I was looking at how you guys handle pricing, letting agencies pass the admin fee to the client instead of paying out of pocket. I think that's a smart way to remove the cost objection entirely. Curious how the split looks between agencies using the free model vs. pay-as-you-go.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "kotini", company: "Kotini", founder: "Kieran Witt", email: "kieran@kotini.co.uk", domain: "kotini.co.uk", threadId: "19e84f1e1cc54b65", messageId: "19e84f1e1cc54b65", subject: "proptech compliance | Telescope intro", body: "<div>Kieran, been thinking more about Kotini. The Nested partnership caught my eye because it feels like a signal that even the more tech-forward agencies are realizing they can't build compliance infrastructure themselves. Going from 250 properties automated to 500 in three months is solid execution, and the OPDA founding membership tells me you're thinking about the data layer beyond just onboarding. I'd be curious how you're thinking about the material information piece long term, specifically whether there's an opportunity to own more of that data flow between agents, conveyancers, and lenders rather than just collecting it on the front end.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "kotini", company: "Kotini", founder: "Kieran Witt", email: "kieran@kotini.co.uk", domain: "kotini.co.uk", threadId: "19e84f1e1cc54b65", messageId: "19e84f1e1cc54b65", subject: "proptech compliance | Telescope intro", body: "<div>Kieran, one more note. We've seen a few companies in adjacent spaces where the initial wedge was compliance or onboarding and they expanded into owning more of the transaction workflow over time. Happy to share some of those learnings if helpful, especially around how the expansion playbook tends to work in regulated industries. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // PARTSPULSE - Email 2, 3, 4
  { slug: "partspulse", company: "PartsPulse", founder: "Steve Blanco", email: "steve@partspulse.ai", domain: "partspulse.ai", threadId: "19e84f3077188561", messageId: "19e84f3077188561", subject: "aftermarket parts intelligence | Telescope intro", body: "<div>Hey Steve, circling back on this. I was looking at how you guys co-developed the platform with Wabash through UP.Labs and I think that's a really interesting way to build, having a real manufacturer pressure-testing the product from day one. Curious how the transition works from that co-development relationship into selling to other OEMs and dealers who might be Wabash competitors.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "partspulse", company: "PartsPulse", founder: "Steve Blanco", email: "steve@partspulse.ai", domain: "partspulse.ai", threadId: "19e84f3077188561", messageId: "19e84f3077188561", subject: "aftermarket parts intelligence | Telescope intro", body: "<div>Steve, been thinking more about PartsPulse. The piece that keeps standing out to me is how fragmented the data is across parts operations. Sales, pricing, and inventory all sitting in separate systems means nobody has a full picture, and the people making decisions are basically guessing. After 12 years at Documoto serving 160+ equipment brands, you've probably seen every version of that problem. I think the interesting question is whether this lands as a tool that individual teams use or whether it becomes the system of record that the whole parts org runs on. Curious how customers are adopting it, whether it starts in one function and spreads or whether they buy the full platform upfront.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "partspulse", company: "PartsPulse", founder: "Steve Blanco", email: "steve@partspulse.ai", domain: "partspulse.ai", threadId: "19e84f3077188561", messageId: "19e84f3077188561", subject: "aftermarket parts intelligence | Telescope intro", body: "<div>Steve, wanted to follow up one more time. I work closely with Chris Gaertner who has spent a lot of time in the supply chain and manufacturing space, including companies like Parabola, Paperless Parts, and Project44. He'd have some useful perspective on how these platforms scale across fragmented industries. Happy to connect you two if it would be helpful to swap notes. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // JUSTWIN - Email 2, 3, 4
  { slug: "justwin", company: "JustWin", founder: "Ted Baxa", email: "ted@justwin.ai", domain: "justwin.ai", threadId: "19e84f34c33c2dd9", messageId: "19e84f34c33c2dd9", subject: "Telescope <> JustWin Intro", body: "<div>Hey Ted, circling back on this. I was looking at the competitive intelligence feature where you pull competitor proposals through public records requests automatically. I think that's a clever angle since most companies bidding on government contracts are flying blind on what actually won last time. Curious how much of the value prop customers respond to first, the opportunity discovery side or the competitive intel side.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "justwin", company: "JustWin", founder: "Ted Baxa", email: "ted@justwin.ai", domain: "justwin.ai", threadId: "19e84f34c33c2dd9", messageId: "19e84f34c33c2dd9", subject: "Telescope <> JustWin Intro", body: "<div>Ted, been thinking more about JustWin. The government contracting process is one of those areas where the friction is so high that it effectively locks out smaller companies who don't have dedicated BD teams or proposal writers on staff. The mission of democratizing access feels right because the current system rewards the companies that are best at paperwork, not necessarily the best at the actual work. Having backers like Mike Rosengarten who built OpenGov is a good signal that people who understand government tech see this the same way. I'd be curious how you're thinking about the education contracts side vs. government, and whether one is pulling ahead as the primary wedge.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "justwin", company: "JustWin", founder: "Ted Baxa", email: "ted@justwin.ai", domain: "justwin.ai", threadId: "19e84f34c33c2dd9", messageId: "19e84f34c33c2dd9", subject: "Telescope <> JustWin Intro", body: "<div>Ted, one more note from me. We've invested in a number of companies that started by making a broken workflow accessible to a broader market and then expanded from there. Happy to share some of those patterns if it would be useful as you think about what comes after opportunity discovery and proposal writing. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // RAMA - Email 2, 3, 4
  { slug: "rama", company: "Rama", founder: "Matt Francis", email: "matt@tryrama.com", domain: "tryrama.com", threadId: "19e84f731eb026df", messageId: "19e84f731eb026df", subject: "Telescope <> Rama Intro", body: "<div>Hey Matt, circling back on this. I was looking at how you guys handle the supplier pricing side, pulling live data from 700+ brokers and distributors and surfacing cheaper alternatives automatically. I think that's the piece that makes this sticky beyond just speeding up quotes. Curious how distributors typically react when they see the pricing gaps for the first time.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "rama", company: "Rama", founder: "Matt Francis", email: "matt@tryrama.com", domain: "tryrama.com", threadId: "19e84f731eb026df", messageId: "19e84f731eb026df", subject: "Telescope <> Rama Intro", body: "<div>Hey Matt, been thinking more about Rama and the Classic Components case study. Finding 21% of parts cheaper across a multi-hundred line opportunity list is a pretty concrete way to show ROI on day one, especially for a distributor that size. I think the interesting strategic question is whether you stay focused on independent distributors or eventually move upstream to the larger guys who have more volume but also more entrenched systems. The 13% revenue per employee lift is the kind of metric that should make this an easy conversation with ops leaders. Would love to dig into how the pipeline is looking and what the sales cycle looks like for a top-10 distributor vs. a mid-market one.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "rama", company: "Rama", founder: "Matt Francis", email: "matt@tryrama.com", domain: "tryrama.com", threadId: "19e84f731eb026df", messageId: "19e84f731eb026df", subject: "Telescope <> Rama Intro", body: "<div>Hey Matt, one more thought here. I work closely with Chris Gaertner who has spent a lot of time in supply chain (Parabola, Paperless Parts, Project44) and I think he'd have some useful perspective on how vertical AI tools like yours tend to expand once the initial wedge is working. Happy to make that intro if it'd be helpful. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // CLAVE - Email 2, 3, 4
  { slug: "clave", company: "Clave", founder: "Tadeo Acosta-Rubio", email: "tadeo@tryclave.ai", domain: "tryclave.ai", threadId: "19e84f89809c0dc8", messageId: "19e84f89809c0dc8", subject: "Telescope <> Clave", body: "<div>Hey Tadeo, circling back on this. I was looking at the Capriotti's case study, specifically the part where you guys replaced five separate spreadsheets with one unified view across 14 stores. I think that's the kind of thing that sounds simple but is actually what gets operators to adopt. Curious whether franchisors are starting to push Clave top-down or if it's still mostly franchisees pulling you in.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "clave", company: "Clave", founder: "Tadeo Acosta-Rubio", email: "tadeo@tryclave.ai", domain: "tryclave.ai", threadId: "19e84f89809c0dc8", messageId: "19e84f89809c0dc8", subject: "Telescope <> Clave", body: "<div>Hey Tadeo, been thinking more about Clave and the go-to-market here. The Churromania numbers are interesting, $64K extra monthly revenue across 45 stores, but what stands out to me is the 60+ hours of manual reporting you guys eliminated. I think in QSR, the people running these locations are not sitting at a desk all day, so anything that requires them to log into a dashboard or pull CSVs just doesn't get used. The fact that operators can just ask a question in chat and get an answer feels like the right interface for this customer. Curious how you're thinking about expanding beyond the brands you're live with today, whether it's going deeper within existing franchise systems or broadening to new ones.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "clave", company: "Clave", founder: "Tadeo Acosta-Rubio", email: "tadeo@tryclave.ai", domain: "tryclave.ai", threadId: "19e84f89809c0dc8", messageId: "19e84f89809c0dc8", subject: "Telescope <> Clave", body: "<div>Hey Tadeo, one last note here. We've spent a lot of time in vertical SaaS for operationally heavy industries, and one pattern we keep seeing is that the companies that win are the ones built by people who actually lived the problem. Growing up in Churromania with 140+ locations gives you and Mateo a level of intuition about franchise operations that's hard to replicate. Happy to connect you with anyone in our network who might be helpful, whether that's other vertical SaaS founders or folks in the franchise world. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // PETRA SECURITY - Email 2, 3, 4
  { slug: "petra_security", company: "Petra Security", founder: "Cooper Edmunds", email: "cooper@petrasecurity.com", domain: "petrasecurity.com", threadId: "19e84f9535a0b024", messageId: "19e84f9535a0b024", subject: "Telescope <> Petra Intro", body: "<div>Hey Cooper, circling back on this. I was looking at the AME Group case study, 133 BEC attacks caught in 144 days with a 56-second mean time to containment. What stood out is that they deployed across 300+ tenants in a single day. Curious how much of the sales motion is driven by MSPs seeing gaps in what Huntress or Blackpoint are catching vs. you guys proactively showing them.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "petra_security", company: "Petra Security", founder: "Cooper Edmunds", email: "cooper@petrasecurity.com", domain: "petrasecurity.com", threadId: "19e84f9535a0b024", messageId: "19e84f9535a0b024", subject: "Telescope <> Petra Intro", body: "<div>Hey Cooper, been thinking more about Petra and the positioning here. I think the decision to go deep on M365 identity threats instead of trying to be a broader security platform is smart, especially selling through MSPs who already have EDR and other tools from different vendors. The 90 hours per month in billable hours reclaimed for AME Group is a really compelling way to frame the ROI, because MSPs are always trying to figure out how to do more with fewer senior engineers. The fact that help desk staff can now handle responses that used to require senior people changes the unit economics for the MSP. Curious whether you're seeing more traction with larger MSPs who have dedicated security teams or smaller ones where this effectively becomes their entire M365 security layer.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "petra_security", company: "Petra Security", founder: "Cooper Edmunds", email: "cooper@petrasecurity.com", domain: "petrasecurity.com", threadId: "19e84f9535a0b024", messageId: "19e84f9535a0b024", subject: "Telescope <> Petra Intro", body: "<div>Hey Cooper, one more thought here. I work closely with Chris Gaertner who invested in Rewst and Auvik and has spent a lot of time in the MSP channel. He also has deep security experience from Axonius and JumpCloud. I think he'd have some useful perspective on how security vendors scale through the MSP ecosystem, and happy to make that intro if it'd be helpful. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // DOMU - Email 2, 3, 4
  { slug: "domu", company: "Domu", founder: "Nico Diaz", email: "nico@domu.ai", domain: "domu.ai", threadId: "19e84f9a5dd3dfe1", messageId: "19e84f9a5dd3dfe1", subject: "Domu + Telescope", body: "<div>Hey Nico, circling back on this. I was reading about how your agents adapt accent and dialect based on who they're calling, like varying the Spanish accent for Mexico vs. Colombia. I think that level of nuance is what separates this from a generic voice bot that just reads a script. Curious how much of the engagement lift you're seeing comes from those adaptive personality features vs. just the basics of timing and channel optimization.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "domu", company: "Domu", founder: "Nico Diaz", email: "nico@domu.ai", domain: "domu.ai", threadId: "19e84f9a5dd3dfe1", messageId: "19e84f9a5dd3dfe1", subject: "Domu + Telescope", body: "<div>Hey Nico, been thinking more about Domu. 70M monthly connected calls is a pretty staggering number for a company your size. I think what's interesting about the compliance angle is that it's not just a checkbox, it's actually a moat. The banks and insurers you're working with can't afford a CFPB violation, so once you're validated and live, switching costs are real. The BNP Paribas result of 40% more right-party contacts is the kind of metric that should make this an easy expansion conversation within those accounts. Curious how much of your growth is coming from expanding within existing clients vs. landing new logos.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "domu", company: "Domu", founder: "Nico Diaz", email: "nico@domu.ai", domain: "domu.ai", threadId: "19e84f9a5dd3dfe1", messageId: "19e84f9a5dd3dfe1", subject: "Domu + Telescope", body: "<div>Hey Nico, one last thought here. I think you guys are at an interesting inflection point, 8 of the top 20 banks and insurers across the Americas is real market validation, and the question becomes how you scale from here without the team growing linearly with revenue. Happy to connect you with anyone in our network who's navigated that kind of scaling challenge in enterprise AI. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" },

  // CERTO - Email 2, 3, 4
  { slug: "certo", company: "Certo", founder: "Bastien Deliege-Coste", email: "bastien@askcerto.com", domain: "askcerto.com", threadId: "19e84fa3be72ea7f", messageId: "19e84fa3be72ea7f", subject: "Telescope <> Certo", body: "<div>Hey Bastien, circling back on this. I was looking at how you guys structured the platform around five distinct modules, ingredient validation, formula compliance, claims, labelling, and market entry. I think starting with the full workflow instead of just one piece makes it harder for customers to outgrow you. Curious whether most customers are adopting all five from day one or starting with one and expanding.</div>", emailNumber: 2, sendDate: "2026-06-03", status: "pending" },
  { slug: "certo", company: "Certo", founder: "Bastien Deliege-Coste", email: "bastien@askcerto.com", domain: "askcerto.com", threadId: "19e84fa3be72ea7f", messageId: "19e84fa3be72ea7f", subject: "Telescope <> Certo", body: "<div>Hey Bastien, been thinking more about Certo. What I keep coming back to is the regulatory monitoring piece, the fact that your system automatically rechecks products when regulations change. I think that's the part that turns this from a one-time review tool into something teams rely on every day. The regulatory landscape for consumer products keeps getting more complex (microplastics, greenwashing rules, allergen classification), and most brands are still managing this with spreadsheets and consultants across 70+ markets. Jean mentioned you guys started by sitting with regulatory teams and watching how they actually work, and I think that kind of ground-up approach matters a lot in a space where the workflows are so specific. Curious how you're thinking about prioritizing which markets and product categories to go deeper on next.</div>", emailNumber: 3, sendDate: "2026-06-06", status: "pending" },
  { slug: "certo", company: "Certo", founder: "Bastien Deliege-Coste", email: "bastien@askcerto.com", domain: "askcerto.com", threadId: "19e84fa3be72ea7f", messageId: "19e84fa3be72ea7f", subject: "Telescope <> Certo", body: "<div>Hey Bastien, one more thought here. As you guys scale into the US market, happy to connect you with folks in our network who have navigated the go-to-market for selling compliance and regulatory tools to enterprise CPG and beauty brands. It's a specific kind of sales motion and having people who've done it before can save a lot of time. If now isn't the right time, totally understand.</div>", emailNumber: 4, sendDate: "2026-06-08", status: "pending" }
];

async function main() {
  console.log('Fetching remote followups.json...');
  const resp = await ghApi('GET', '/contents/followups.json');
  const content = Buffer.from(resp.content, 'base64').toString('utf-8');
  const config = JSON.parse(content);
  const remoteSha = resp.sha;

  console.log('Current pending entries: ' + config.pending.length);
  config.pending.push(...newEntries);
  console.log('After adding ' + newEntries.length + ' entries: ' + config.pending.length);

  const updated = JSON.stringify(config, null, 2) + '\n';
  fs.writeFileSync(configPath, updated);

  console.log('Pushing to GitHub...');
  const encoded = Buffer.from(updated.replace(/\r\n/g, '\n')).toString('base64');
  await ghApi('PUT', '/contents/followups.json', {
    message: '[auto] add follow-up cadences for 16 companies (Jun 1 batch)',
    content: encoded,
    sha: remoteSha
  });
  console.log('Done! Pushed ' + newEntries.length + ' new follow-up entries to remote.');
}

main().catch(err => { console.error('FATAL:', err.message); process.exit(1); });
